language: node_js
node_js:
  - "4.4.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - sudo apt-get install npm
  - npm config set registry http://registry.npmjs.org/
  - npm install
  # install codecov.io
  - npm install codecov.io
script:
  - npm test
  # Run build and test
  - npm run build
  - npm run comparedist
  # check if mock data up to data, show warning
  - |
      npm run syncmock || { \
        echo 'WARNING: mock data out of sync with API return calls'; 
      }
after_success:
 # upload coverage data to codecov.io
 - cat coverage/*/lcov.info | codecov
cache:
  directories:
    - node_modules
