language: node_js
node_js:
  - "v6.11.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - npm config set registry http://registry.npmjs.org/
  - npm install
  # install codecov.io
  - npm install codecov.io
script:
  # make sure json/ts client is in sync
  - bash src/test/check_api_sync.sh
  # Run build
  - npm run build
  # Run test
  - npm test
  # check if mock data up to data, show warning
  - |
      npm run syncmock || { \
        echo 'WARNING: mock data out of sync with API return calls'; 
      }
after_success:
 # upload coverage data to codecov.io
 - cat test/fixtures/outputs/lcov.info | codecov
cache:
  directories:
    - node_modules
