FROM circleci/node:8.12.0-browsers
MAINTAINER Pim van Nierop <pim@thehyve.nl>

LABEL Description="End-2-end test image for cBioPortal frontend"

USER root

COPY . /cbioportal-frontend
RUN cd /cbioportal-frontend && npm install --global yarn@1.13.0 && cd end-to-end-tests && yarn install

CMD /cbioportal-frontend/end-to-end-tests/local_database/docker/screenshottest.sh