declare module '*.scss';
declare module '*.json';
declare module 'query-string';
declare module 'rc-tooltip';
declare module 'react-file-download';
declare module 'react-zeroclipboard';
declare module 'reactable';
declare module 'reactableMSK';
declare module 'redux-seamless-immutable';
declare module 'webpack-raphael';
declare module 'render-if';
declare type PartialPick<T, K extends keyof T> = Partial<Pick<T, K>>;
declare module 'rc-tooltip';
declare module 'underscore';
