// allow these file patterns to be imported
declare module '*.scss';
declare module '*.json';

// these packages are missing typings
declare module 'object-sizeof';
declare module 'save-svg-as-png'
declare module 'react-file-download';
declare module 'react-select-checked';
declare module 'react-zeroclipboard';
declare module 'reactableMSK';
declare module 'redux-seamless-immutable';
declare module 'render-if';
declare module 'react-if';
declare module 'react-collapse';
declare module 'webpack-raphael';
declare module 'javascript-natural-sort';
declare module 'expect';
declare module 'expect-jsx';
declare module 'parameter-validator';
declare module 'better-react-spinkit';
declare module 'recompose/withContext';
declare module 'react-bootstrap-autosuggest';
declare module 'react-text-truncate';
declare module 'react-resize-detector';
declare module 'react-rangeslider';
declare module 'jStat';
declare module 'svgsaver';
declare module 'addthis-snippet';
declare module 'd3-dsv';
declare module 'd3';
declare module 'victory';
declare module 'universal-ga';
declare module 'mixpanel-browser';
declare module 'measure-text';
declare module 'contrast';
declare module 'react-spinkit';
declare module 'react-portal';
declare module 'little-loader';
declare module 'igv/dist/igv.esm.js';
declare module 'react-mfb';
