FROM circleci/node:8.12.0-browsers
MAINTAINER Pim van Nierop <pim@thehyve.nl>

LABEL Description="End-2-end test image for cBioPortal frontend"

USER root

COPY . /cbioportal-frontend
RUN npm install --global yarn@1.13.0 && \
    yarn build && \
    cd /cbioportal-frontend/end-to-end-tests && \
    yarn install --frozen-lockfile

CMD bash -c 'cd cbioportal-frontend && \
    yarn serveDistLocalDb & \
    cd end-to-end-tests && \
    ./node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome "2.42" && \
    ./node_modules/webdriver-manager/bin/webdriver-manager start --versions.chrome "2.42" & \
    sleep 30; \
    (curl --insecure https://localhost:3000 || curl http://localhost:3000) > /dev/null && \
    yarn run test-webdriver-manager'