// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react-spinkit/react-spinkit.d.ts
declare module "react-spinkit" {
    import { Component } from 'react';

    interface Props {
        spinnerName?: string;
    }

    class Spinner extends Component<Props, {}> { }

    export default Spinner;
}
