language: node_js
node_js:
- '6'
script:
- npm run build
- npm run test
# generate version in package.json using git describe --tags
- sed -i "s|\"version\".*|\"version\":\"$(git describe --tags | sed 's/^v//g')\",|g" package.json
deploy:
  provider: npm
  email: cbioportal@gmail.com
  skip_cleanup: true
  api_key:
    secure: EVdXGpTxgB6g+8rmWXR7fv3hUgDgbmiUgIYmPAw4In6wOfIymQMwcxQ0rzbZlqPuhMCUKrHjzWo6pcTqoYF862wssfZozy2e8tlIVVbAqJhJ+w9wmFzPuJlCPt4vpXrRe+yBNR5dJqYeX12jZFANWN8Iro6f5wXdq5Jn5H8CTt0=
  on:
    tags: true
    repo: cBioPortal/oncoprintjs
