language: node_js
node_js:
- '6'
before_deploy:
- npm run build
- mv ./dist/oncoprint-bundle.js ./index.js
- cp -r ./dist/* ./
- rm -rf dist
# generate version in package.json using git describe --tags
- sed -i "s/\"oncoprintjs\",/\"oncoprintjs\",\n\ \ \"version\":\"$(git describe --tags | sed 's/^v//g')\",/g" package.json
deploy:
  provider: npm
  email: cbioportal@gmail.com
  skip_cleanup: true
  api_key:
    secure: ZC3+VW3XnrUF0wPtTxjYm3IDtfICmFJ8q1LYJVWBR8WTq5xrqXHv3/WRshr+br4CtLWHfUXF+Ii+ThT3A5X6+9LfodAN7HwFy3kTwcS4zxv9UrEcy/fJmeyPNmWzjS2h+ZERHoBV5uHDAtWi+XAqAeNfu+5yLa9Ax7rPhhwXrr4=
  on:
    tags: true
    repo: cBioPortal/oncoprintjs
