declare const styles: {
  readonly "addButton": string;
  readonly "addMtbButton": string;
  readonly "addOncoKbButton": string;
  readonly "alterationUl": string;
  readonly "armDiv": string;
  readonly "checkbox-align": string;
  readonly "criteriaHr": string;
  readonly "deleteButton": string;
  readonly "deleteMtbButton": string;
  readonly "edit": string;
  readonly "editButton": string;
  readonly "editContainer": string;
  readonly "editIcon": string;
  readonly "firstLeft": string;
  readonly "firstRight": string;
  readonly "genomicInfoContainer": string;
  readonly "genomicSpan": string;
  readonly "icon": string;
  readonly "loginButton": string;
  readonly "marginLeft": string;
  readonly "marginRight": string;
  readonly "powered": string;
  readonly "reasoningContainer": string;
  readonly "reasoningInfoContainer": string;
  readonly "repositionButton": string;
  readonly "sampleIdsContainer": string;
  readonly "secondLeft": string;
  readonly "secondRight": string;
  readonly "successBox": string;
  readonly "testButton": string;
  readonly "tooltip": string;
};
export = styles;

