export const inlineStyles = {
    container: {
        display: 'flex',
        alignItems: 'center',
        gap: 14,
        padding: '8px 14px',
        backgroundColor: '#fff',
        fontSize: 13,
        flexWrap: 'wrap' as const,
        minHeight: 32,
    },
    transcriptRow: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 18,
        padding: '4px 14px 8px',
        backgroundColor: '#fff',
        fontSize: 13,
    },
    fusionName: {
        fontWeight: 700 as const,
        fontSize: 15,
        whiteSpace: 'nowrap' as const,
        paddingTop: 2,
    },
    separator: {
        color: '#333',
        fontWeight: 700 as const,
    },
    coordinates: {
        color: '#777',
        fontSize: 12,
        whiteSpace: 'nowrap' as const,
        paddingTop: 4,
    },
    checkboxGroup: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 0,
        maxHeight: 120,
        overflowY: 'auto' as const,
    },
    checkboxLabel: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        fontSize: 11,
        cursor: 'pointer',
        padding: '1px 0',
    },
    checkbox: {
        margin: 0,
        cursor: 'pointer',
    },
    label: {
        fontSize: 11,
        fontWeight: 600 as const,
        color: '#666',
        marginBottom: 2,
    },
    forteStar: {
        color: '#f0ad4e',
        fontSize: 11,
        marginLeft: 2,
    },
    badge: {
        display: 'inline-block',
        fontSize: 10,
        padding: '1px 6px',
        borderRadius: 3,
        fontWeight: 600 as const,
    },
    significanceBadge: {
        backgroundColor: '#dff0d8',
        color: '#3c763d',
        border: '1px solid #d6e9c6',
    },
    metaBadge: {
        backgroundColor: '#eee',
        color: '#555',
    },
    spacer: {
        flex: 1,
    },
    selectorWrapper: {
        display: 'flex',
        flexDirection: 'column' as const,
    },
    badgeRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        paddingTop: 4,
    },
    buildToggle: {
        display: 'flex',
        alignItems: 'center',
        gap: 2,
        border: '1px solid #ccc',
        borderRadius: 3,
        overflow: 'hidden' as const,
        fontSize: 11,
        fontWeight: 600 as const,
    },
    buildButton: {
        padding: '2px 8px',
        cursor: 'pointer',
        border: 'none',
        backgroundColor: '#f5f5f5',
        color: '#666',
        fontSize: 11,
        fontWeight: 600 as const,
    },
    buildButtonActive: {
        backgroundColor: '#337ab7',
        color: '#fff',
    },
};
