export const GENETIC_PROFILE_MUTATIONS_SUFFIX = '_mutations';
export const GENETIC_PROFILE_UNCALLED_MUTATIONS_SUFFIX = `${GENETIC_PROFILE_MUTATIONS_SUFFIX}_uncalled`;
export const MUTATION_STATUS_GERMLINE = 'Germline';
