export enum FeatureFlagEnum {
    STUDY_VIEW_STRUCT_VAR_TABLE = 'STUDY_VIEW_STRUCT_VAR_TABLE',
    LEFT_TRUNCATION_ADJUSTMENT = 'LEFT_TRUNCATION_ADJUSTMENT',
    GENERIC_ASSAY_GROUP_COMPARISON = 'GENERIC_ASSAY_GROUP_COMPARISON',
}
