export enum FeatureFlagEnum {
    LEFT_TRUNCATION_ADJUSTMENT = 'LEFT_TRUNCATION_ADJUSTMENT',
    PATIENT_MRNA_TAB = 'patientMRNATab',
    GENE_SPECIFIC_VIOLIN_PLOT = 'geneSpecificViolinPlot',
    EMBEDDINGS = 'EMBEDDINGS',
}
