version: '3'

services:
  keycloak:
    networks:
    - cbio-net
    container_name: keycloak
    image: jboss/keycloak:11.0.3
    restart: unless-stopped
    depends_on:
    - kcdb
    ports:
    - "8081:8080"
    volumes:
    - $PWD/../keycloak/keycloak-config-generated.json:/tmp/realm.json:ro
    environment:
    - KEYCLOAK_IMPORT=/tmp/realm.json
    - DB_VENDOR=mysql
    - DB_ADDR=kcdb
    - DB_USER=keycloak
    - DB_PORT=3306
    - DB_PASSWORD=password
    - DB_DATABASE=keycloak
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - JDBC_PARAMS=${KEYCLOAK_JDBC_PARAMS:-useSSL=false}

  kcdb:
    networks:
    - cbio-net
    image: mysql:5.7
    container_name: kcdb
    restart: unless-stopped
    volumes:
    - /tmp/kcdb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=keycloak
    command: --ssl=0
    
networks:
  cbio-net: 
