FROM circleci/node:15.2.1-browsers
MAINTAINER Pim van Nierop <pim@thehyve.nl>
LABEL Description="End-2-end test image for cBioPortal frontend"
USER root

CMD /cbioportal-frontend/end-to-end-test/local/docker_compose/docker/screenshottest.sh
