export * from './model/ClinicalDataBySampleId';
export * from './model/RequestStatus';
export * from './model/BackwardCompatibilityAliases';

// Import and re-export the backward-compatible API wrapper classes
export { default as CBioPortalAPI } from './api/CBioPortalAPICompat';
export { default as CBioPortalAPIInternal } from './api/CBioPortalAPIInternalCompat';

// Also export the raw generated APIs for those who need them
export { default as CBioPortalAPIRaw } from './generated/CBioPortalAPI';
export { default as CBioPortalAPIInternalRaw } from './generated/CBioPortalAPIInternal';

// Export all types from generated APIs - this includes the real Sample type
export * from './generated/CBioPortalAPI';
// For backward compatibility, export SampleDTO as Sample since application code
// expects Sample to have properties like sampleId and studyId (which are on SampleDTO)
export { SampleDTO as Sample } from './generated/CBioPortalAPIInternal';
// For CBioPortalAPIInternal, we need selective exports to avoid conflicts
//
// Export types that still have their original names in generated code
export {
    AlterationCountByGene,
    AlterationCountByStructuralVariant,
    AlterationEnrichment,
    AlterationFilter,
    AndedPatientTreatmentFilters,
    AndedSampleTreatmentFilters,
    BinsGeneratorConfig,
    CaseListDataCount,
    ClinicalAttribute,
    ClinicalAttributeCount,
    ClinicalAttributeCountFilter,
    ClinicalData,
    ClinicalDataBin,
    ClinicalDataBinCountFilter,
    ClinicalDataBinFilter,
    ClinicalDataCount,
    ClinicalDataCountFilter,
    ClinicalDataCountItem,
    ClinicalDataFilter,
    ClinicalEvent,
    ClinicalEventAttributeRequest,
    ClinicalEventData,
    ClinicalEventRequest,
    ClinicalEventRequestIdentifier,
    ClinicalEventSample,
    ClinicalEventTypeCount,
    ClinicalViolinPlotBoxData,
    ClinicalViolinPlotData,
    ClinicalViolinPlotIndividualPoint,
    ClinicalViolinPlotRowData,
    CoExpression,
    CoExpressionFilter,
    CopyNumberCount,
    CopyNumberCountByGene,
    CopyNumberCountIdentifier,
    CountSummary,
    CustomDriverAnnotationReport,
    DataAccessToken,
    DataFilter,
    DataFilterValue,
    DensityPlotBin,
    DensityPlotData,
    GeneFilter,
    GeneFilterQuery,
    GenericAssayBinaryEnrichment,
    GenericAssayCategoricalEnrichment,
    GenericAssayCountSummary,
    GenericAssayDataBin,
    GenericAssayDataBinCountFilter,
    GenericAssayDataBinFilter,
    GenericAssayDataCount,
    GenericAssayDataCountFilter,
    GenericAssayDataCountItem,
    GenericAssayDataFilter,
    GenericAssayEnrichment,
    Geneset,
    GenesetCorrelation,
    GenesetDataFilterCriteria,
    GenesetHierarchyInfo,
    GenesetMolecularData,
    GenomicDataBin,
    GenomicDataBinCountFilter,
    GenomicDataBinFilter,
    GenomicDataCount,
    GenomicDataCountFilter,
    GenomicDataCountItem,
    GenomicDataFilter,
    GenomicEnrichment,
    Gistic,
    GisticToGene,
    Group,
    GroupFilter,
    GroupStatistics,
    MolecularProfileCaseIdentifier,
    MolecularProfileCasesGroupAndAlterationTypeFilter,
    MolecularProfileCasesGroupFilter,
    MrnaPercentile,
    MutSig,
    MutationCountByPosition,
    MutationDataFilter,
    MutationPositionIdentifier,
    MutationSpectrum,
    MutationSpectrumFilter,
    NamespaceAttribute,
    NamespaceAttributeCount,
    NamespaceAttributeCountFilter,
    NamespaceComparisonFilter,
    NamespaceData,
    NamespaceDataCount,
    NamespaceDataCountFilter,
    NamespaceDataCountItem,
    NamespaceDataFilter,
    OredPatientTreatmentFilters,
    OredSampleTreatmentFilters,
    PatientIdentifier,
    PatientTreatment,
    PatientTreatmentFilter,
    PatientTreatmentReport,
    PatientTreatmentRow,
    ReferenceGenomeGene,
    ResourceData,
    ResourceDefinition,
    SampleClinicalDataCollection,
    SampleIdentifier,
    SampleMolecularIdentifier,
    SampleTreatmentFilter,
    SampleTreatmentReport,
    SampleTreatmentRow,
    StructuralVariant,
    StructuralVariantFilter,
    StructuralVariantFilterQuery,
    StructuralVariantGeneSubQuery,
    StructuralVariantQuery,
    StudyViewFilter,
    StudyViewStructuralVariantFilter,
    SurvivalRequest,
    VariantCount,
    VariantCountIdentifier,
} from './generated/CBioPortalAPIInternal';
