export * from './model/ClinicalDataBySampleId';
export * from './model/RequestStatus';

export * from './generated/CBioPortalAPI';
export { default as CBioPortalAPI } from './generated/CBioPortalAPI';

// We need to do named exports here. We cannot simply do
//  export * from './generated/CBioPortalAPIInternal';
// because both CBioPortalAPI and CBioPortalAPIInternal include models with the same name
// which causes TS errors
export {
    AlterationCountByGene,
    AlterationCountByStructuralVariant,
    AlterationEnrichment,
    AlterationFilter,
    AndedPatientTreatmentFilters,
    AndedSampleTreatmentFilters,
    BinsGeneratorConfig,
    CaseListDataCount,
    ClinicalAttribute,
    ClinicalAttributeCount,
    ClinicalAttributeCountFilter,
    ClinicalData,
    ClinicalDataBin,
    ClinicalDataBinCountFilter,
    ClinicalDataBinFilter,
    ClinicalDataCount,
    ClinicalDataCountFilter,
    ClinicalDataCountItem,
    ClinicalDataEnrichment,
    ClinicalDataFilter,
    ClinicalEvent,
    ClinicalEventAttributeRequest,
    ClinicalEventData,
    ClinicalEventRequest,
    ClinicalEventRequestIdentifier,
    ClinicalEventSample,
    ClinicalEventTypeCount,
    ClinicalViolinPlotBoxData,
    ClinicalViolinPlotData,
    ClinicalViolinPlotIndividualPoint,
    ClinicalViolinPlotRowData,
    CoExpression,
    CoExpressionFilter,
    CopyNumberCount,
    CopyNumberCountByGene,
    CopyNumberCountIdentifier,
    CountSummary,
    CustomDriverAnnotationReport,
    DataAccessToken,
    DataFilter,
    DataFilterValue,
    DensityPlotBin,
    DensityPlotData,
    GeneFilter,
    GeneFilterQuery,
    GenericAssayBinaryEnrichment,
    GenericAssayCategoricalEnrichment,
    GenericAssayCountSummary,
    GenericAssayDataBin,
    GenericAssayDataBinCountFilter,
    GenericAssayDataBinFilter,
    GenericAssayDataCount,
    GenericAssayDataCountFilter,
    GenericAssayDataCountItem,
    GenericAssayDataFilter,
    GenericAssayEnrichment,
    Geneset,
    GenesetCorrelation,
    GenesetDataFilterCriteria,
    GenesetHierarchyInfo,
    GenesetMolecularData,
    GenomicDataBin,
    GenomicDataBinCountFilter,
    GenomicDataBinFilter,
    GenomicDataCount,
    GenomicDataCountFilter,
    GenomicDataCountItem,
    GenomicDataFilter,
    GenomicEnrichment,
    Gistic,
    GisticToGene,
    Group,
    GroupFilter,
    GroupStatistics,
    MolecularProfileCaseIdentifier,
    MolecularProfileCasesGroupAndAlterationTypeFilter,
    MolecularProfileCasesGroupFilter,
    MrnaPercentile,
    MutSig,
    MutationCountByPosition,
    MutationDataFilter,
    MutationPositionIdentifier,
    MutationSpectrum,
    MutationSpectrumFilter,
    NamespaceAttribute,
    NamespaceAttributeCount,
    NamespaceAttributeCountFilter,
    NamespaceComparisonFilter,
    NamespaceData,
    NamespaceDataCount,
    NamespaceDataCountFilter,
    NamespaceDataCountItem,
    NamespaceDataFilter,
    OredPatientTreatmentFilters,
    OredSampleTreatmentFilters,
    PatientIdentifier,
    PatientTreatmentFilter,
    PatientTreatmentRow,
    ReferenceGenomeGene,
    ResourceData,
    ResourceDefinition,
    Sample,
    SampleClinicalDataCollection,
    SampleIdentifier,
    SampleMolecularIdentifier,
    SampleTreatmentFilter,
    SampleTreatmentRow,
    StructuralVariant,
    StructuralVariantFilter,
    StructuralVariantFilterQuery,
    StructuralVariantGeneSubQuery,
    StructuralVariantQuery,
    StudyViewFilter,
    StudyViewStructuralVariantFilter,
    SurvivalRequest,
    VariantCount,
    VariantCountIdentifier,
    default as CBioPortalAPIInternal,
} from './generated/CBioPortalAPIInternal';

// Type aliases for treatment reports (wrapper types not in generated API)
// These types wrap the API response arrays into report objects
export type PatientTreatment = import('./generated/CBioPortalAPIInternal').PatientTreatmentRow;
export type PatientTreatmentReport = {
    patientTreatments: import('./generated/CBioPortalAPIInternal').PatientTreatmentRow[];
    totalSamples: number;
    totalPatients: number;
};
export type SampleTreatmentReport = {
    treatments: import('./generated/CBioPortalAPIInternal').SampleTreatmentRow[];
    totalSamples: number;
};
